name: Format JSON on Commit

on:
  push:
    paths:
      - '**.json'
  workflow_dispatch:

jobs:
  format-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install jq
        run: sudo apt-get install jq
      - name: Find and format all JSON files
        run: |
          find . -name '*.json' -not -path './.git/*' | while read file; do
            jq . "$file" > tmp.json && mv tmp.json "$file"
          done
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto-format JSON files'
          branch: ${{ github.ref }}
